### ISSUE TITLE
Is this project still active?

### ISSUE THREAD

**Issue by skx** [goruby/goruby#55]
### What version of Go are you using (`go version`)?

1.11

### What operating system and processor architecture are you using (`go env`)?

linux, amd64.

### What version of GoRuby are you using (git show -s --format=%H or goruby -version)?

`ee5b7274d84c124a2bd3b3d6f1e2c78d31148cc5`

In short I wondered if you're still working upon this project?  There are a couple of things I see in the TODO-list of the README file that I'd be happy to contribute.  But it might be that you've stalled, or wish to proceed under your own pace.

As an example it seems like supporting '\t', '\n', etc should be a simple matter of updating `lexString` in `lexer/lexer.go`.  I'd be happy to do that, but it might be you have a different approach you might prefer.

**Comment by mitch000001** [comment]
Hey,
The development was somewhat halted because I struggle with the Parser at the moment. The syntax of Ruby is quite complex and I am not yet sure if a recursive descendent parser can handle that. Or at least, as I wrote in literature it would be possible through outfactoring but I am not sure that it's still readable afterwards.

For the conceptual idea of how my plan was to implement things: I am focusing on "the hard parts" first, meaning that the goal at the beginning was to get a running interpreter and to see how it feels if you add open classes and all that stuff. This was accomplished. The current state is a limited but running interpreter with a very limited syntactical understanding of Ruby.

To your questions: feel free to contribute things, and if you feel that there are a lot of low hanging fruits to implement, go for it.

As long as I or anyone who wants  to contribute doesn't have a good idea how to proceed with the Parser this will wait in its current state. Suggestions highly welcome :)

**Comment by mitch000001** [comment]
@skx how do you feel about getting a contributor team member? Also, are you in gophers slack? #goruby Channel on Gophers Slack

**Comment by skx** [comment]
I'd be happy to be invited; since that would let me close those issues which I noted were "done".

But I'm not one for realtime chat except in very rare cases.

**Comment by mitch000001** [comment]
@skx done.

**Comment by skx** [comment]
I appreciate the invitation; I've closed some issues and I'm looking at making some minor updates based on the notes in the README.

As you say the hard-stuff is hard, and I suspect I can't help so much there, but that aside it's a fun learning experience.
